server:
  port: 0
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    name: "account-service.yml"
    import: "optional:configserver:http://localhost:1000"
  application:
    name: account-command-service

---
spring:
  config:
    import: "optional:configserver:http://configuration-service:1000"
    activate:
      on-profile: docker
