name: push-on-branch

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'

jobs:
  account-command-api:
    uses: bettor-league/reusable-workflow/.github/workflows/build-java-microservice.yml@master
    with:
      maven_build_core: true
      maven_pom_location: 'account-command-api'
      upload_artifact: true
    secrets: inherit