name: push-on-master

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-account-core:
    uses: bettor-league/reusable-workflow/.github/workflows/java-maven-ci.yml@master
    with:
      maven_command: 'clean deploy'
      maven_profiles: 'default'
    secrets: inherit